! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2002-2024, Lawrence Livermore National Security
! and Southern Methodist University.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fnvector_cuda_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_cuda_policies_mod
 use fsundials_core_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 integer, parameter :: swig_cmem_const_bit = 2
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 type, public :: SWIGTYPE_p_SUNMemory
  type(SwigClassWrapper), public :: swigdata
 end type
 type, public :: SWIGTYPE_p_SUNCudaExecPolicy
  type(SwigClassWrapper), public :: swigdata
 end type
 type, public :: SWIGTYPE_p_SUNMemoryHelper
  type(SwigClassWrapper), public :: swigdata
 end type
 ! struct struct _N_VectorContent_Cuda
 type, public :: N_VectorContent_Cuda_
  type(SwigClassWrapper), public :: swigdata
 contains
  procedure :: set_length => swigf__N_VectorContent_Cuda_length_set
  procedure :: get_length => swigf__N_VectorContent_Cuda_length_get
  procedure :: set_own_helper => swigf__N_VectorContent_Cuda_own_helper_set
  procedure :: get_own_helper => swigf__N_VectorContent_Cuda_own_helper_get
  procedure :: set_host_data => swigf__N_VectorContent_Cuda_host_data_set
  procedure :: get_host_data => swigf__N_VectorContent_Cuda_host_data_get
  procedure :: set_device_data => swigf__N_VectorContent_Cuda_device_data_set
  procedure :: get_device_data => swigf__N_VectorContent_Cuda_device_data_get
  procedure :: set_stream_exec_policy => swigf__N_VectorContent_Cuda_stream_exec_policy_set
  procedure :: get_stream_exec_policy => swigf__N_VectorContent_Cuda_stream_exec_policy_get
  procedure :: set_reduce_exec_policy => swigf__N_VectorContent_Cuda_reduce_exec_policy_set
  procedure :: get_reduce_exec_policy => swigf__N_VectorContent_Cuda_reduce_exec_policy_get
  procedure :: set_mem_helper => swigf__N_VectorContent_Cuda_mem_helper_set
  procedure :: get_mem_helper => swigf__N_VectorContent_Cuda_mem_helper_get
  procedure :: set_priv => swigf__N_VectorContent_Cuda_priv_set
  procedure :: get_priv => swigf__N_VectorContent_Cuda_priv_get
  procedure :: release => swigf_release__N_VectorContent_Cuda
  procedure, private :: swigf__N_VectorContent_Cuda_op_assign__
  generic :: assignment(=) => swigf__N_VectorContent_Cuda_op_assign__
 end type N_VectorContent_Cuda_
 public :: FN_VNewEmpty_Cuda
 public :: FN_VNew_Cuda
 public :: FN_VNewManaged_Cuda
 public :: FN_VNewWithMemHelp_Cuda
 public :: FN_VMake_Cuda
 public :: FN_VMakeManaged_Cuda
 public :: FN_VSetHostArrayPointer_Cuda
 public :: FN_VSetDeviceArrayPointer_Cuda
 public :: FN_VIsManagedMemory_Cuda
 public :: FN_VCopyToDevice_Cuda
 public :: FN_VCopyFromDevice_Cuda
 public :: FN_VGetLength_Cuda
 public :: FN_VGetVectorID_Cuda
 public :: FN_VCloneEmpty_Cuda
 public :: FN_VClone_Cuda
 public :: FN_VDestroy_Cuda
 public :: FN_VSpace_Cuda
 public :: FN_VLinearSum_Cuda
 public :: FN_VConst_Cuda
 public :: FN_VProd_Cuda
 public :: FN_VDiv_Cuda
 public :: FN_VScale_Cuda
 public :: FN_VAbs_Cuda
 public :: FN_VInv_Cuda
 public :: FN_VAddConst_Cuda
 public :: FN_VDotProd_Cuda
 public :: FN_VMaxNorm_Cuda
 public :: FN_VWrmsNorm_Cuda
 public :: FN_VWrmsNormMask_Cuda
 public :: FN_VMin_Cuda
 public :: FN_VWL2Norm_Cuda
 public :: FN_VL1Norm_Cuda
 public :: FN_VCompare_Cuda
 public :: FN_VInvTest_Cuda
 public :: FN_VConstrMask_Cuda
 public :: FN_VMinQuotient_Cuda
 public :: FN_VLinearCombination_Cuda
 public :: FN_VScaleAddMulti_Cuda
 public :: FN_VDotProdMulti_Cuda
 public :: FN_VLinearSumVectorArray_Cuda
 public :: FN_VScaleVectorArray_Cuda
 public :: FN_VConstVectorArray_Cuda
 public :: FN_VScaleAddMultiVectorArray_Cuda
 public :: FN_VLinearCombinationVectorArray_Cuda
 public :: FN_VWrmsNormVectorArray_Cuda
 public :: FN_VWrmsNormMaskVectorArray_Cuda
 public :: FN_VWSqrSumLocal_Cuda
 public :: FN_VWSqrSumMaskLocal_Cuda
 public :: FN_VBufSize_Cuda
 public :: FN_VBufPack_Cuda
 public :: FN_VBufUnpack_Cuda
 public :: FN_VPrint_Cuda
 public :: FN_VPrintFile_Cuda
 public :: FN_VEnableFusedOps_Cuda
 public :: FN_VEnableLinearCombination_Cuda
 public :: FN_VEnableScaleAddMulti_Cuda
 public :: FN_VEnableDotProdMulti_Cuda
 public :: FN_VEnableLinearSumVectorArray_Cuda
 public :: FN_VEnableScaleVectorArray_Cuda
 public :: FN_VEnableConstVectorArray_Cuda
 public :: FN_VEnableWrmsNormVectorArray_Cuda
 public :: FN_VEnableWrmsNormMaskVectorArray_Cuda
 public :: FN_VEnableScaleAddMultiVectorArray_Cuda
 public :: FN_VEnableLinearCombinationVectorArray_Cuda

 public :: FN_VGetDeviceArrayPointer_Cuda
 public :: FN_VGetHostArrayPointer_Cuda 
 public :: FN_VSetKernelExecPolicy_Cuda


! WRAPPER DECLARATIONS
interface
subroutine swigc__N_VectorContent_Cuda_length_set(farg1, farg2) &
bind(C, name="_wrap__N_VectorContent_Cuda_length_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT64_T), intent(in) :: farg2
end subroutine

function swigc__N_VectorContent_Cuda_length_get(farg1) &
bind(C, name="_wrap__N_VectorContent_Cuda_length_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT64_T) :: fresult
end function

subroutine swigc__N_VectorContent_Cuda_own_helper_set(farg1, farg2) &
bind(C, name="_wrap__N_VectorContent_Cuda_own_helper_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT), intent(in) :: farg2
end subroutine

function swigc__N_VectorContent_Cuda_own_helper_get(farg1) &
bind(C, name="_wrap__N_VectorContent_Cuda_own_helper_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc__N_VectorContent_Cuda_host_data_set(farg1, farg2) &
bind(C, name="_wrap__N_VectorContent_Cuda_host_data_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc__N_VectorContent_Cuda_host_data_get(farg1) &
bind(C, name="_wrap__N_VectorContent_Cuda_host_data_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc__N_VectorContent_Cuda_device_data_set(farg1, farg2) &
bind(C, name="_wrap__N_VectorContent_Cuda_device_data_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc__N_VectorContent_Cuda_device_data_get(farg1) &
bind(C, name="_wrap__N_VectorContent_Cuda_device_data_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc__N_VectorContent_Cuda_stream_exec_policy_set(farg1, farg2) &
bind(C, name="_wrap__N_VectorContent_Cuda_stream_exec_policy_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc__N_VectorContent_Cuda_stream_exec_policy_get(farg1) &
bind(C, name="_wrap__N_VectorContent_Cuda_stream_exec_policy_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc__N_VectorContent_Cuda_reduce_exec_policy_set(farg1, farg2) &
bind(C, name="_wrap__N_VectorContent_Cuda_reduce_exec_policy_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc__N_VectorContent_Cuda_reduce_exec_policy_get(farg1) &
bind(C, name="_wrap__N_VectorContent_Cuda_reduce_exec_policy_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc__N_VectorContent_Cuda_mem_helper_set(farg1, farg2) &
bind(C, name="_wrap__N_VectorContent_Cuda_mem_helper_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc__N_VectorContent_Cuda_mem_helper_get(farg1) &
bind(C, name="_wrap__N_VectorContent_Cuda_mem_helper_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(SwigClassWrapper) :: fresult
end function

subroutine swigc__N_VectorContent_Cuda_priv_set(farg1, farg2) &
bind(C, name="_wrap__N_VectorContent_Cuda_priv_set")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc__N_VectorContent_Cuda_priv_get(farg1) &
bind(C, name="_wrap__N_VectorContent_Cuda_priv_get") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper) :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_delete__N_VectorContent_Cuda(farg1) &
bind(C, name="_wrap_delete__N_VectorContent_Cuda")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
end subroutine

subroutine swigc__N_VectorContent_Cuda_op_assign__(farg1, farg2) &
bind(C, name="_wrap__N_VectorContent_Cuda_op_assign__")
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
type(SwigClassWrapper), intent(inout) :: farg1
type(SwigClassWrapper) :: farg2
end subroutine

function swigc_FN_VNewEmpty_Cuda(farg1) &
bind(C, name="_wrap_FN_VNewEmpty_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

function swigc_FN_VNew_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VNew_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR) :: fresult
end function

function swigc_FN_VNewManaged_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VNewManaged_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR) :: fresult
end function

function swigc_FN_VNewWithMemHelp_Cuda(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FN_VNewWithMemHelp_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_INT64_T), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(SwigClassWrapper) :: farg3
type(C_PTR), value :: farg4
type(C_PTR) :: fresult
end function

function swigc_FN_VMake_Cuda(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FN_VMake_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR) :: fresult
end function

function swigc_FN_VMakeManaged_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VMakeManaged_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR) :: fresult
end function

subroutine swigc_FN_VSetHostArrayPointer_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VSetHostArrayPointer_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
end subroutine

subroutine swigc_FN_VSetDeviceArrayPointer_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VSetDeviceArrayPointer_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_FN_VIsManagedMemory_Cuda(farg1) &
bind(C, name="_wrap_FN_VIsManagedMemory_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

subroutine swigc_FN_VCopyToDevice_Cuda(farg1) &
bind(C, name="_wrap_FN_VCopyToDevice_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

subroutine swigc_FN_VCopyFromDevice_Cuda(farg1) &
bind(C, name="_wrap_FN_VCopyFromDevice_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_FN_VGetLength_Cuda(farg1) &
bind(C, name="_wrap_FN_VGetLength_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_FN_VGetVectorID_Cuda(farg1) &
bind(C, name="_wrap_FN_VGetVectorID_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FN_VCloneEmpty_Cuda(farg1) &
bind(C, name="_wrap_FN_VCloneEmpty_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

function swigc_FN_VClone_Cuda(farg1) &
bind(C, name="_wrap_FN_VClone_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_FN_VDestroy_Cuda(farg1) &
bind(C, name="_wrap_FN_VDestroy_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

subroutine swigc_FN_VSpace_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VSpace_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
end subroutine

subroutine swigc_FN_VLinearSum_Cuda(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_FN_VLinearSum_Cuda")
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
type(C_PTR), value :: farg2
real(C_DOUBLE), intent(in) :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
end subroutine

subroutine swigc_FN_VConst_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VConst_Cuda")
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
type(C_PTR), value :: farg2
end subroutine

subroutine swigc_FN_VProd_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VProd_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
end subroutine

subroutine swigc_FN_VDiv_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VDiv_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
end subroutine

subroutine swigc_FN_VScale_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VScale_Cuda")
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
end subroutine

subroutine swigc_FN_VAbs_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VAbs_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
end subroutine

subroutine swigc_FN_VInv_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VInv_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
end subroutine

subroutine swigc_FN_VAddConst_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VAddConst_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE), intent(in) :: farg2
type(C_PTR), value :: farg3
end subroutine

function swigc_FN_VDotProd_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VDotProd_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
real(C_DOUBLE) :: fresult
end function

function swigc_FN_VMaxNorm_Cuda(farg1) &
bind(C, name="_wrap_FN_VMaxNorm_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE) :: fresult
end function

function swigc_FN_VWrmsNorm_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VWrmsNorm_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
real(C_DOUBLE) :: fresult
end function

function swigc_FN_VWrmsNormMask_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VWrmsNormMask_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
real(C_DOUBLE) :: fresult
end function

function swigc_FN_VMin_Cuda(farg1) &
bind(C, name="_wrap_FN_VMin_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE) :: fresult
end function

function swigc_FN_VWL2Norm_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VWL2Norm_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
real(C_DOUBLE) :: fresult
end function

function swigc_FN_VL1Norm_Cuda(farg1) &
bind(C, name="_wrap_FN_VL1Norm_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
real(C_DOUBLE) :: fresult
end function

subroutine swigc_FN_VCompare_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VCompare_Cuda")
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
end subroutine

function swigc_FN_VInvTest_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VInvTest_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VConstrMask_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VConstrMask_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FN_VMinQuotient_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VMinQuotient_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
real(C_DOUBLE) :: fresult
end function

function swigc_FN_VLinearCombination_Cuda(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FN_VLinearCombination_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_FN_VScaleAddMulti_Cuda(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_FN_VScaleAddMulti_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
integer(C_INT) :: fresult
end function

function swigc_FN_VDotProdMulti_Cuda(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FN_VDotProdMulti_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_FN_VLinearSumVectorArray_Cuda(farg1, farg2, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_FN_VLinearSumVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
type(C_PTR), value :: farg3
real(C_DOUBLE), intent(in) :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
integer(C_INT) :: fresult
end function

function swigc_FN_VScaleVectorArray_Cuda(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FN_VScaleVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_FN_VConstVectorArray_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VConstVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
real(C_DOUBLE), intent(in) :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FN_VScaleAddMultiVectorArray_Cuda(farg1, farg2, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_FN_VScaleAddMultiVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
integer(C_INT) :: fresult
end function

function swigc_FN_VLinearCombinationVectorArray_Cuda(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_FN_VLinearCombinationVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
integer(C_INT), intent(in) :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
integer(C_INT) :: fresult
end function

function swigc_FN_VWrmsNormVectorArray_Cuda(farg1, farg2, farg3, farg4) &
bind(C, name="_wrap_FN_VWrmsNormVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
integer(C_INT) :: fresult
end function

function swigc_FN_VWrmsNormMaskVectorArray_Cuda(farg1, farg2, farg3, farg4, farg5) &
bind(C, name="_wrap_FN_VWrmsNormMaskVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
integer(C_INT), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
type(C_PTR), value :: farg4
type(C_PTR), value :: farg5
integer(C_INT) :: fresult
end function

function swigc_FN_VWSqrSumLocal_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VWSqrSumLocal_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
real(C_DOUBLE) :: fresult
end function

function swigc_FN_VWSqrSumMaskLocal_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VWSqrSumMaskLocal_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
real(C_DOUBLE) :: fresult
end function

function swigc_FN_VBufSize_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VBufSize_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VBufPack_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VBufPack_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VBufUnpack_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VBufUnpack_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

subroutine swigc_FN_VPrint_Cuda(farg1) &
bind(C, name="_wrap_FN_VPrint_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

subroutine swigc_FN_VPrintFile_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VPrintFile_Cuda")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
end subroutine

function swigc_FN_VEnableFusedOps_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableFusedOps_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableLinearCombination_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableLinearCombination_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableScaleAddMulti_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableScaleAddMulti_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableDotProdMulti_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableDotProdMulti_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableLinearSumVectorArray_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableLinearSumVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableScaleVectorArray_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableScaleVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableConstVectorArray_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableConstVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableWrmsNormVectorArray_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableWrmsNormVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableWrmsNormMaskVectorArray_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableWrmsNormMaskVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableScaleAddMultiVectorArray_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableScaleAddMultiVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function

function swigc_FN_VEnableLinearCombinationVectorArray_Cuda(farg1, farg2) &
bind(C, name="_wrap_FN_VEnableLinearCombinationVectorArray_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT), intent(in) :: farg2
integer(C_INT) :: fresult
end function


function swigc_FN_VGetDeviceArrayPointer_Cuda(farg1) &
bind(C, name="_wrap_FN_VGetDeviceArrayPointer_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

function swigc_FN_VGetHostArrayPointer_Cuda(farg1) &
bind(C, name="_wrap_FN_VGetHostArrayPointer_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

function swigc_FN_VSetKernelExecPolicy_Cuda(farg1, farg2, farg3) &
bind(C, name="_wrap_FN_VSetKernelExecPolicy_Cuda") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
subroutine swigf__N_VectorContent_Cuda_length_set(self, length)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(in) :: self
integer(C_INT64_T), intent(in) :: length
type(SwigClassWrapper) :: farg1 
integer(C_INT64_T) :: farg2 

farg1 = self%swigdata
farg2 = length
call swigc__N_VectorContent_Cuda_length_set(farg1, farg2)
end subroutine

function swigf__N_VectorContent_Cuda_length_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
class(N_VectorContent_Cuda_), intent(in) :: self
integer(C_INT64_T) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc__N_VectorContent_Cuda_length_get(farg1)
swig_result = fresult
end function

subroutine swigf__N_VectorContent_Cuda_own_helper_set(self, own_helper)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(in) :: self
integer(C_INT), intent(in) :: own_helper
type(SwigClassWrapper) :: farg1 
integer(C_INT) :: farg2 

farg1 = self%swigdata
farg2 = own_helper
call swigc__N_VectorContent_Cuda_own_helper_set(farg1, farg2)
end subroutine

function swigf__N_VectorContent_Cuda_own_helper_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
class(N_VectorContent_Cuda_), intent(in) :: self
integer(C_INT) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc__N_VectorContent_Cuda_own_helper_get(farg1)
swig_result = fresult
end function

subroutine swigf__N_VectorContent_Cuda_host_data_set(self, host_data)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(in) :: self
type(SWIGTYPE_p_SUNMemory), intent(in) :: host_data
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = host_data%swigdata
call swigc__N_VectorContent_Cuda_host_data_set(farg1, farg2)
end subroutine

function swigf__N_VectorContent_Cuda_host_data_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_SUNMemory) :: swig_result
class(N_VectorContent_Cuda_), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc__N_VectorContent_Cuda_host_data_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf__N_VectorContent_Cuda_device_data_set(self, device_data)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(in) :: self
type(SWIGTYPE_p_SUNMemory), intent(in) :: device_data
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = device_data%swigdata
call swigc__N_VectorContent_Cuda_device_data_set(farg1, farg2)
end subroutine

function swigf__N_VectorContent_Cuda_device_data_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_SUNMemory) :: swig_result
class(N_VectorContent_Cuda_), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc__N_VectorContent_Cuda_device_data_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf__N_VectorContent_Cuda_stream_exec_policy_set(self, stream_exec_policy)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(in) :: self
class(SWIGTYPE_p_SUNCudaExecPolicy), intent(in) :: stream_exec_policy
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = stream_exec_policy%swigdata
call swigc__N_VectorContent_Cuda_stream_exec_policy_set(farg1, farg2)
end subroutine

function swigf__N_VectorContent_Cuda_stream_exec_policy_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_SUNCudaExecPolicy) :: swig_result
class(N_VectorContent_Cuda_), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc__N_VectorContent_Cuda_stream_exec_policy_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf__N_VectorContent_Cuda_reduce_exec_policy_set(self, reduce_exec_policy)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(in) :: self
class(SWIGTYPE_p_SUNCudaExecPolicy), intent(in) :: reduce_exec_policy
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = reduce_exec_policy%swigdata
call swigc__N_VectorContent_Cuda_reduce_exec_policy_set(farg1, farg2)
end subroutine

function swigf__N_VectorContent_Cuda_reduce_exec_policy_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_SUNCudaExecPolicy) :: swig_result
class(N_VectorContent_Cuda_), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc__N_VectorContent_Cuda_reduce_exec_policy_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf__N_VectorContent_Cuda_mem_helper_set(self, mem_helper)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(in) :: self
type(SWIGTYPE_p_SUNMemoryHelper), intent(in) :: mem_helper
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = mem_helper%swigdata
call swigc__N_VectorContent_Cuda_mem_helper_set(farg1, farg2)
end subroutine

function swigf__N_VectorContent_Cuda_mem_helper_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SWIGTYPE_p_SUNMemoryHelper) :: swig_result
class(N_VectorContent_Cuda_), intent(in) :: self
type(SwigClassWrapper) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc__N_VectorContent_Cuda_mem_helper_get(farg1)
swig_result%swigdata = fresult
end function

subroutine swigf__N_VectorContent_Cuda_priv_set(self, priv)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(in) :: self
type(C_PTR) :: priv
type(SwigClassWrapper) :: farg1 
type(C_PTR) :: farg2 

farg1 = self%swigdata
farg2 = priv
call swigc__N_VectorContent_Cuda_priv_set(farg1, farg2)
end subroutine

function swigf__N_VectorContent_Cuda_priv_get(self) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(C_PTR) :: swig_result
class(N_VectorContent_Cuda_), intent(in) :: self
type(C_PTR) :: fresult 
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
fresult = swigc__N_VectorContent_Cuda_priv_get(farg1)
swig_result = fresult
end function

subroutine swigf_release__N_VectorContent_Cuda(self)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(inout) :: self
type(SwigClassWrapper) :: farg1 

farg1 = self%swigdata
if (btest(farg1%cmemflags, swig_cmem_own_bit)) then
call swigc_delete__N_VectorContent_Cuda(farg1)
endif
farg1%cptr = C_NULL_PTR
farg1%cmemflags = 0
self%swigdata = farg1
end subroutine

subroutine swigf__N_VectorContent_Cuda_op_assign__(self, other)
use, intrinsic :: ISO_C_BINDING
class(N_VectorContent_Cuda_), intent(inout) :: self
type(N_VectorContent_Cuda_), intent(in) :: other
type(SwigClassWrapper) :: farg1 
type(SwigClassWrapper) :: farg2 

farg1 = self%swigdata
farg2 = other%swigdata
call swigc__N_VectorContent_Cuda_op_assign__(farg1, farg2)
self%swigdata = farg1
end subroutine

function FN_VNewEmpty_Cuda(sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 

farg1 = sunctx
fresult = swigc_FN_VNewEmpty_Cuda(farg1)
call c_f_pointer(fresult, swig_result)
end function

function FN_VNew_Cuda(length, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
integer(C_INT64_T), intent(in) :: length
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT64_T) :: farg1 
type(C_PTR) :: farg2 

farg1 = length
farg2 = sunctx
fresult = swigc_FN_VNew_Cuda(farg1, farg2)
call c_f_pointer(fresult, swig_result)
end function

function FN_VNewManaged_Cuda(length, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
integer(C_INT64_T), intent(in) :: length
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT64_T) :: farg1 
type(C_PTR) :: farg2 

farg1 = length
farg2 = sunctx
fresult = swigc_FN_VNewManaged_Cuda(farg1, farg2)
call c_f_pointer(fresult, swig_result)
end function

function FN_VNewWithMemHelp_Cuda(length, use_managed_mem, helper, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
integer(C_INT64_T), intent(in) :: length
integer(C_INT), intent(in) :: use_managed_mem
type(SWIGTYPE_p_SUNMemoryHelper), intent(in) :: helper
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT64_T) :: farg1 
integer(C_INT) :: farg2 
type(SwigClassWrapper) :: farg3 
type(C_PTR) :: farg4 

farg1 = length
farg2 = use_managed_mem
farg3 = helper%swigdata
farg4 = sunctx
fresult = swigc_FN_VNewWithMemHelp_Cuda(farg1, farg2, farg3, farg4)
call c_f_pointer(fresult, swig_result)
end function

function FN_VMake_Cuda(length, h_vdata, d_vdata, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
integer(C_INT64_T), intent(in) :: length
real(C_DOUBLE), dimension(*), target, intent(inout) :: h_vdata
real(C_DOUBLE), dimension(*), target, intent(inout) :: d_vdata
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT64_T) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 

farg1 = length
farg2 = c_loc(h_vdata(1))
farg3 = c_loc(d_vdata(1))
farg4 = sunctx
fresult = swigc_FN_VMake_Cuda(farg1, farg2, farg3, farg4)
call c_f_pointer(fresult, swig_result)
end function

function FN_VMakeManaged_Cuda(length, vdata, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
integer(C_INT64_T), intent(in) :: length
real(C_DOUBLE), dimension(*), target, intent(inout) :: vdata
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT64_T) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = length
farg2 = c_loc(vdata(1))
farg3 = sunctx
fresult = swigc_FN_VMakeManaged_Cuda(farg1, farg2, farg3)
call c_f_pointer(fresult, swig_result)
end function

subroutine FN_VSetHostArrayPointer_Cuda(h_vdata, v)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(*), target, intent(inout) :: h_vdata
type(N_Vector), target, intent(inout) :: v
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(h_vdata(1))
farg2 = c_loc(v)
call swigc_FN_VSetHostArrayPointer_Cuda(farg1, farg2)
end subroutine

subroutine FN_VSetDeviceArrayPointer_Cuda(d_vdata, v)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(*), target, intent(inout) :: d_vdata
type(N_Vector), target, intent(inout) :: v
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(d_vdata(1))
farg2 = c_loc(v)
call swigc_FN_VSetDeviceArrayPointer_Cuda(farg1, farg2)
end subroutine

function FN_VIsManagedMemory_Cuda(x) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: x
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(x)
fresult = swigc_FN_VIsManagedMemory_Cuda(farg1)
swig_result = fresult
end function

subroutine FN_VCopyToDevice_Cuda(v)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: v
type(C_PTR) :: farg1 

farg1 = c_loc(v)
call swigc_FN_VCopyToDevice_Cuda(farg1)
end subroutine

subroutine FN_VCopyFromDevice_Cuda(v)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: v
type(C_PTR) :: farg1 

farg1 = c_loc(v)
call swigc_FN_VCopyFromDevice_Cuda(farg1)
end subroutine

function FN_VGetLength_Cuda(x) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(N_Vector), target, intent(inout) :: x
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(x)
fresult = swigc_FN_VGetLength_Cuda(farg1)
swig_result = fresult
end function

function FN_VGetVectorID_Cuda(arg0) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(N_Vector_ID) :: swig_result
type(N_Vector), target, intent(inout) :: arg0
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(arg0)
fresult = swigc_FN_VGetVectorID_Cuda(farg1)
swig_result = fresult
end function

function FN_VCloneEmpty_Cuda(w) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
type(N_Vector), target, intent(inout) :: w
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(w)
fresult = swigc_FN_VCloneEmpty_Cuda(farg1)
call c_f_pointer(fresult, swig_result)
end function

function FN_VClone_Cuda(w) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), pointer :: swig_result
type(N_Vector), target, intent(inout) :: w
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(w)
fresult = swigc_FN_VClone_Cuda(farg1)
call c_f_pointer(fresult, swig_result)
end function

subroutine FN_VDestroy_Cuda(v)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: v
type(C_PTR) :: farg1 

farg1 = c_loc(v)
call swigc_FN_VDestroy_Cuda(farg1)
end subroutine

subroutine FN_VSpace_Cuda(v, lrw, liw)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: v
integer(C_INT64_T), dimension(*), target, intent(inout) :: lrw
integer(C_INT64_T), dimension(*), target, intent(inout) :: liw
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(v)
farg2 = c_loc(lrw(1))
farg3 = c_loc(liw(1))
call swigc_FN_VSpace_Cuda(farg1, farg2, farg3)
end subroutine

subroutine FN_VLinearSum_Cuda(a, x, b, y, z)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: a
type(N_Vector), target, intent(inout) :: x
real(C_DOUBLE), intent(in) :: b
type(N_Vector), target, intent(inout) :: y
type(N_Vector), target, intent(inout) :: z
real(C_DOUBLE) :: farg1 
type(C_PTR) :: farg2 
real(C_DOUBLE) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 

farg1 = a
farg2 = c_loc(x)
farg3 = b
farg4 = c_loc(y)
farg5 = c_loc(z)
call swigc_FN_VLinearSum_Cuda(farg1, farg2, farg3, farg4, farg5)
end subroutine

subroutine FN_VConst_Cuda(c, z)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: c
type(N_Vector), target, intent(inout) :: z
real(C_DOUBLE) :: farg1 
type(C_PTR) :: farg2 

farg1 = c
farg2 = c_loc(z)
call swigc_FN_VConst_Cuda(farg1, farg2)
end subroutine

subroutine FN_VProd_Cuda(x, y, z)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: y
type(N_Vector), target, intent(inout) :: z
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(x)
farg2 = c_loc(y)
farg3 = c_loc(z)
call swigc_FN_VProd_Cuda(farg1, farg2, farg3)
end subroutine

subroutine FN_VDiv_Cuda(x, y, z)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: y
type(N_Vector), target, intent(inout) :: z
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(x)
farg2 = c_loc(y)
farg3 = c_loc(z)
call swigc_FN_VDiv_Cuda(farg1, farg2, farg3)
end subroutine

subroutine FN_VScale_Cuda(c, x, z)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: c
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: z
real(C_DOUBLE) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c
farg2 = c_loc(x)
farg3 = c_loc(z)
call swigc_FN_VScale_Cuda(farg1, farg2, farg3)
end subroutine

subroutine FN_VAbs_Cuda(x, z)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: z
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = c_loc(z)
call swigc_FN_VAbs_Cuda(farg1, farg2)
end subroutine

subroutine FN_VInv_Cuda(x, z)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: z
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = c_loc(z)
call swigc_FN_VInv_Cuda(farg1, farg2)
end subroutine

subroutine FN_VAddConst_Cuda(x, b, z)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: x
real(C_DOUBLE), intent(in) :: b
type(N_Vector), target, intent(inout) :: z
type(C_PTR) :: farg1 
real(C_DOUBLE) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(x)
farg2 = b
farg3 = c_loc(z)
call swigc_FN_VAddConst_Cuda(farg1, farg2, farg3)
end subroutine

function FN_VDotProd_Cuda(x, y) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: y
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = c_loc(y)
fresult = swigc_FN_VDotProd_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VMaxNorm_Cuda(x) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: x
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(x)
fresult = swigc_FN_VMaxNorm_Cuda(farg1)
swig_result = fresult
end function

function FN_VWrmsNorm_Cuda(x, w) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: w
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = c_loc(w)
fresult = swigc_FN_VWrmsNorm_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VWrmsNormMask_Cuda(x, w, id) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: w
type(N_Vector), target, intent(inout) :: id
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(x)
farg2 = c_loc(w)
farg3 = c_loc(id)
fresult = swigc_FN_VWrmsNormMask_Cuda(farg1, farg2, farg3)
swig_result = fresult
end function

function FN_VMin_Cuda(x) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: x
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(x)
fresult = swigc_FN_VMin_Cuda(farg1)
swig_result = fresult
end function

function FN_VWL2Norm_Cuda(x, w) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: w
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = c_loc(w)
fresult = swigc_FN_VWL2Norm_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VL1Norm_Cuda(x) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: x
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(x)
fresult = swigc_FN_VL1Norm_Cuda(farg1)
swig_result = fresult
end function

subroutine FN_VCompare_Cuda(c, x, z)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: c
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: z
real(C_DOUBLE) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c
farg2 = c_loc(x)
farg3 = c_loc(z)
call swigc_FN_VCompare_Cuda(farg1, farg2, farg3)
end subroutine

function FN_VInvTest_Cuda(x, z) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: z
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = c_loc(z)
fresult = swigc_FN_VInvTest_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VConstrMask_Cuda(c, x, m) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: c
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: m
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(c)
farg2 = c_loc(x)
farg3 = c_loc(m)
fresult = swigc_FN_VConstrMask_Cuda(farg1, farg2, farg3)
swig_result = fresult
end function

function FN_VMinQuotient_Cuda(num, denom) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: num
type(N_Vector), target, intent(inout) :: denom
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(num)
farg2 = c_loc(denom)
fresult = swigc_FN_VMinQuotient_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VLinearCombination_Cuda(nvec, c, x, z) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
real(C_DOUBLE), dimension(*), target, intent(inout) :: c
type(C_PTR) :: x
type(N_Vector), target, intent(inout) :: z
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 

farg1 = nvec
farg2 = c_loc(c(1))
farg3 = x
farg4 = c_loc(z)
fresult = swigc_FN_VLinearCombination_Cuda(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FN_VScaleAddMulti_Cuda(nvec, c, x, y, z) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
real(C_DOUBLE), dimension(*), target, intent(inout) :: c
type(N_Vector), target, intent(inout) :: x
type(C_PTR) :: y
type(C_PTR) :: z
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 

farg1 = nvec
farg2 = c_loc(c(1))
farg3 = c_loc(x)
farg4 = y
farg5 = z
fresult = swigc_FN_VScaleAddMulti_Cuda(farg1, farg2, farg3, farg4, farg5)
swig_result = fresult
end function

function FN_VDotProdMulti_Cuda(nvec, x, y, dotprods) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
type(N_Vector), target, intent(inout) :: x
type(C_PTR) :: y
real(C_DOUBLE), dimension(*), target, intent(inout) :: dotprods
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 

farg1 = nvec
farg2 = c_loc(x)
farg3 = y
farg4 = c_loc(dotprods(1))
fresult = swigc_FN_VDotProdMulti_Cuda(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FN_VLinearSumVectorArray_Cuda(nvec, a, x, b, y, z) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
real(C_DOUBLE), intent(in) :: a
type(C_PTR) :: x
real(C_DOUBLE), intent(in) :: b
type(C_PTR) :: y
type(C_PTR) :: z
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
real(C_DOUBLE) :: farg2 
type(C_PTR) :: farg3 
real(C_DOUBLE) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 

farg1 = nvec
farg2 = a
farg3 = x
farg4 = b
farg5 = y
farg6 = z
fresult = swigc_FN_VLinearSumVectorArray_Cuda(farg1, farg2, farg3, farg4, farg5, farg6)
swig_result = fresult
end function

function FN_VScaleVectorArray_Cuda(nvec, c, x, z) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
real(C_DOUBLE), dimension(*), target, intent(inout) :: c
type(C_PTR) :: x
type(C_PTR) :: z
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 

farg1 = nvec
farg2 = c_loc(c(1))
farg3 = x
farg4 = z
fresult = swigc_FN_VScaleVectorArray_Cuda(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FN_VConstVectorArray_Cuda(nvec, c, z) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
real(C_DOUBLE), intent(in) :: c
type(C_PTR) :: z
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
real(C_DOUBLE) :: farg2 
type(C_PTR) :: farg3 

farg1 = nvec
farg2 = c
farg3 = z
fresult = swigc_FN_VConstVectorArray_Cuda(farg1, farg2, farg3)
swig_result = fresult
end function

function FN_VScaleAddMultiVectorArray_Cuda(nvec, nsum, a, x, y, z) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
integer(C_INT), intent(in) :: nsum
real(C_DOUBLE), dimension(*), target, intent(inout) :: a
type(C_PTR) :: x
type(C_PTR), target, intent(inout) :: y
type(C_PTR), target, intent(inout) :: z
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
integer(C_INT) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 

farg1 = nvec
farg2 = nsum
farg3 = c_loc(a(1))
farg4 = x
farg5 = c_loc(y)
farg6 = c_loc(z)
fresult = swigc_FN_VScaleAddMultiVectorArray_Cuda(farg1, farg2, farg3, farg4, farg5, farg6)
swig_result = fresult
end function

function FN_VLinearCombinationVectorArray_Cuda(nvec, nsum, c, x, z) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
integer(C_INT), intent(in) :: nsum
real(C_DOUBLE), dimension(*), target, intent(inout) :: c
type(C_PTR), target, intent(inout) :: x
type(C_PTR) :: z
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
integer(C_INT) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 

farg1 = nvec
farg2 = nsum
farg3 = c_loc(c(1))
farg4 = c_loc(x)
farg5 = z
fresult = swigc_FN_VLinearCombinationVectorArray_Cuda(farg1, farg2, farg3, farg4, farg5)
swig_result = fresult
end function

function FN_VWrmsNormVectorArray_Cuda(nvec, x, w, nrm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
type(C_PTR) :: x
type(C_PTR) :: w
real(C_DOUBLE), dimension(*), target, intent(inout) :: nrm
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 

farg1 = nvec
farg2 = x
farg3 = w
farg4 = c_loc(nrm(1))
fresult = swigc_FN_VWrmsNormVectorArray_Cuda(farg1, farg2, farg3, farg4)
swig_result = fresult
end function

function FN_VWrmsNormMaskVectorArray_Cuda(nvec, x, w, id, nrm) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
integer(C_INT), intent(in) :: nvec
type(C_PTR) :: x
type(C_PTR) :: w
type(N_Vector), target, intent(inout) :: id
real(C_DOUBLE), dimension(*), target, intent(inout) :: nrm
integer(C_INT) :: fresult 
integer(C_INT) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 
type(C_PTR) :: farg4 
type(C_PTR) :: farg5 

farg1 = nvec
farg2 = x
farg3 = w
farg4 = c_loc(id)
farg5 = c_loc(nrm(1))
fresult = swigc_FN_VWrmsNormMaskVectorArray_Cuda(farg1, farg2, farg3, farg4, farg5)
swig_result = fresult
end function

function FN_VWSqrSumLocal_Cuda(x, w) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: w
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = c_loc(w)
fresult = swigc_FN_VWSqrSumLocal_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VWSqrSumMaskLocal_Cuda(x, w, id) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: w
type(N_Vector), target, intent(inout) :: id
real(C_DOUBLE) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(x)
farg2 = c_loc(w)
farg3 = c_loc(id)
fresult = swigc_FN_VWSqrSumMaskLocal_Cuda(farg1, farg2, farg3)
swig_result = fresult
end function

function FN_VBufSize_Cuda(x, size) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: x
integer(C_INT64_T), dimension(*), target, intent(inout) :: size
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = c_loc(size(1))
fresult = swigc_FN_VBufSize_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VBufPack_Cuda(x, buf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(C_PTR) :: buf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = buf
fresult = swigc_FN_VBufPack_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VBufUnpack_Cuda(x, buf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(C_PTR) :: buf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(x)
farg2 = buf
fresult = swigc_FN_VBufUnpack_Cuda(farg1, farg2)
swig_result = fresult
end function

subroutine FN_VPrint_Cuda(v)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: v
type(C_PTR) :: farg1 

farg1 = c_loc(v)
call swigc_FN_VPrint_Cuda(farg1)
end subroutine

subroutine FN_VPrintFile_Cuda(v, outfile)
use, intrinsic :: ISO_C_BINDING
type(N_Vector), target, intent(inout) :: v
type(C_PTR) :: outfile
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(v)
farg2 = outfile
call swigc_FN_VPrintFile_Cuda(farg1, farg2)
end subroutine

function FN_VEnableFusedOps_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableFusedOps_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableLinearCombination_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableLinearCombination_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableScaleAddMulti_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableScaleAddMulti_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableDotProdMulti_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableDotProdMulti_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableLinearSumVectorArray_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableLinearSumVectorArray_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableScaleVectorArray_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableScaleVectorArray_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableConstVectorArray_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableConstVectorArray_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableWrmsNormVectorArray_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableWrmsNormVectorArray_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableWrmsNormMaskVectorArray_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableWrmsNormMaskVectorArray_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableScaleAddMultiVectorArray_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableScaleAddMultiVectorArray_Cuda(farg1, farg2)
swig_result = fresult
end function

function FN_VEnableLinearCombinationVectorArray_Cuda(v, tf) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: v
integer(C_INT), intent(in) :: tf
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT) :: farg2 

farg1 = c_loc(v)
farg2 = tf
fresult = swigc_FN_VEnableLinearCombinationVectorArray_Cuda(farg1, farg2)
swig_result = fresult
end function


function FN_VGetDeviceArrayPointer_Cuda(v) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
type(N_Vector), target, intent(inout) :: v
type(C_PTR) :: fresult
type(C_PTR) :: farg1

farg1 = c_loc(v)
fresult = swigc_FN_VGetDeviceArrayPointer_Cuda(farg1)
call c_f_pointer(fresult, swig_result, [FN_VGetLength_Cuda(v)])
end function

function FN_VGetHostArrayPointer_Cuda(v) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
type(N_Vector), target, intent(inout) :: v
type(C_PTR) :: fresult
type(C_PTR) :: farg1

farg1 = c_loc(v)
fresult = swigc_FN_VGetHostArrayPointer_Cuda(farg1)
call c_f_pointer(fresult, swig_result, [FN_VGetLength_Cuda(v)])
end function

function FN_VSetKernelExecPolicy_Cuda(x, stream_exec_policy, reduce_exec_policy) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(N_Vector), target, intent(inout) :: x
type(SUNCudaThreadDirectExecPolicy), target, intent(in) :: stream_exec_policy
type(SUNCudaBlockReduceExecPolicy), target, intent(in) :: reduce_exec_policy
integer(C_INT) :: fresult 
type(C_PTR) :: farg1
type(C_PTR) :: farg2
type(C_PTR) :: farg3

farg1 = c_loc(x)
farg2 = c_loc(stream_exec_policy)
farg3 = c_loc(reduce_exec_policy)

fresult = swigc_FN_VSetKernelExecPolicy_Cuda(farg1, farg2, farg3)
swig_result = fresult
end function


end module
