! This file was automatically generated by SWIG (http://www.swig.org).
! Version 4.0.0
!
! Do not make changes to this file unless you know what you are doing--modify
! the SWIG interface file instead.

! ---------------------------------------------------------------
! Programmer(s): Auto-generated by swig.
! ---------------------------------------------------------------
! SUNDIALS Copyright Start
! Copyright (c) 2002-2024, Lawrence Livermore National Security
! and Southern Methodist University.
! All rights reserved.
!
! See the top-level LICENSE and NOTICE files for details.
!
! SPDX-License-Identifier: BSD-3-Clause
! SUNDIALS Copyright End
! ---------------------------------------------------------------

module fsunmatrix_magmadense_mod
 use, intrinsic :: ISO_C_BINDING
 use fsundials_core_mod
 implicit none
 private

 ! DECLARATION CONSTRUCTS

 integer, parameter :: swig_cmem_own_bit = 0
 integer, parameter :: swig_cmem_rvalue_bit = 1
 integer, parameter :: swig_cmem_const_bit = 2
 type, bind(C) :: SwigClassWrapper
  type(C_PTR), public :: cptr = C_NULL_PTR
  integer(C_INT), public :: cmemflags = 0
 end type
 type, public :: SWIGTYPE_p_SUNMemoryType
  type(SwigClassWrapper), public :: swigdata
 end type
 type, public :: SWIGTYPE_p_SUNMemoryHelper
  type(SwigClassWrapper), public :: swigdata
 end type
 public :: FSUNMatrix_MagmaDense
 public :: FSUNMatrix_MagmaDenseBlock
 public :: FSUNMatrix_MagmaDense_Print
 public :: FSUNMatrix_MagmaDense_LData
 public :: FSUNMatrix_MagmaDense_Rows
 public :: FSUNMatrix_MagmaDense_Columns
 public :: FSUNMatrix_MagmaDense_BlockRows
 public :: FSUNMatrix_MagmaDense_BlockColumns
 public :: FSUNMatrix_MagmaDense_BlockLData
 public :: FSUNMatrix_MagmaDense_NumBlocks
 public :: FSUNMatrix_MagmaDense_CopyToDevice
 public :: FSUNMatrix_MagmaDense_CopyFromDevice
 public :: FSUNMatGetID_MagmaDense
 public :: FSUNMatClone_MagmaDense
 public :: FSUNMatDestroy_MagmaDense
 public :: FSUNMatZero_MagmaDense
 public :: FSUNMatCopy_MagmaDense
 public :: FSUNMatScaleAdd_MagmaDense
 public :: FSUNMatScaleAddI_MagmaDense
 public :: FSUNMatMatvecSetup_MagmaDense
 public :: FSUNMatMatvec_MagmaDense
 public :: FSUNMatSpace_MagmaDense

 public :: FSUNMatrix_MagmaDense_Data
 public :: FSUNMatrix_MagmaDense_BlockData
 public :: FSUNMatrix_MagmaDense_Block
 public :: FSUNMatrix_MagmaDense_Column
 public :: FSUNMatrix_MagmaDense_BlockColumn


! WRAPPER DECLARATIONS
interface
function swigc_FSUNMatrix_MagmaDense(farg1, farg2, farg3, farg4, farg5, farg6) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_INT64_T), intent(in) :: farg1
integer(C_INT64_T), intent(in) :: farg2
type(SwigClassWrapper) :: farg3
type(SwigClassWrapper) :: farg4
type(C_PTR), value :: farg5
type(C_PTR), value :: farg6
type(C_PTR) :: fresult
end function

function swigc_FSUNMatrix_MagmaDenseBlock(farg1, farg2, farg3, farg4, farg5, farg6, farg7) &
bind(C, name="_wrap_FSUNMatrix_MagmaDenseBlock") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
import :: swigclasswrapper
integer(C_INT64_T), intent(in) :: farg1
integer(C_INT64_T), intent(in) :: farg2
integer(C_INT64_T), intent(in) :: farg3
type(SwigClassWrapper) :: farg4
type(SwigClassWrapper) :: farg5
type(C_PTR), value :: farg6
type(C_PTR), value :: farg7
type(C_PTR) :: fresult
end function

subroutine swigc_FSUNMatrix_MagmaDense_Print(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_Print")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_FSUNMatrix_MagmaDense_LData(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_LData") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_Rows(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_Rows") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_Columns(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_Columns") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_BlockRows(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_BlockRows") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_BlockColumns(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_BlockColumns") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_BlockLData(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_BlockLData") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_NumBlocks(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_NumBlocks") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_CopyToDevice(farg1, farg2) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_CopyToDevice") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_CopyFromDevice(farg1, farg2) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_CopyFromDevice") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNMatGetID_MagmaDense(farg1) &
bind(C, name="_wrap_FSUNMatGetID_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNMatClone_MagmaDense(farg1) &
bind(C, name="_wrap_FSUNMatClone_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

subroutine swigc_FSUNMatDestroy_MagmaDense(farg1) &
bind(C, name="_wrap_FSUNMatDestroy_MagmaDense")
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
end subroutine

function swigc_FSUNMatZero_MagmaDense(farg1) &
bind(C, name="_wrap_FSUNMatZero_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNMatCopy_MagmaDense(farg1, farg2) &
bind(C, name="_wrap_FSUNMatCopy_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNMatScaleAdd_MagmaDense(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNMatScaleAdd_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNMatScaleAddI_MagmaDense(farg1, farg2) &
bind(C, name="_wrap_FSUNMatScaleAddI_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), intent(in) :: farg1
type(C_PTR), value :: farg2
integer(C_INT) :: fresult
end function

function swigc_FSUNMatMatvecSetup_MagmaDense(farg1) &
bind(C, name="_wrap_FSUNMatMatvecSetup_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT) :: fresult
end function

function swigc_FSUNMatMatvec_MagmaDense(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNMatMatvec_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function

function swigc_FSUNMatSpace_MagmaDense(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNMatSpace_MagmaDense") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR), value :: farg2
type(C_PTR), value :: farg3
integer(C_INT) :: fresult
end function


function swigc_FSUNMatrix_MagmaDense_Data(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_Data") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_BlockData(farg1) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_BlockData") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
type(C_PTR) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_Block(farg1, farg2) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_Block") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T), intent(in) :: farg2
type(C_PTR) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_Column(farg1, farg2) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_Column") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T), intent(in) :: farg2
type(C_PTR) :: fresult
end function

function swigc_FSUNMatrix_MagmaDense_BlockColumn(farg1, farg2, farg3) &
bind(C, name="_wrap_FSUNMatrix_MagmaDense_BlockColumn") &
result(fresult)
use, intrinsic :: ISO_C_BINDING
type(C_PTR), value :: farg1
integer(C_INT64_T), intent(in) :: farg2
integer(C_INT64_T), intent(in) :: farg3
type(C_PTR) :: fresult
end function

end interface


contains
 ! MODULE SUBPROGRAMS
function FSUNMatrix_MagmaDense(m, n, memtype, memhelper, queue, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNMatrix), pointer :: swig_result
integer(C_INT64_T), intent(in) :: m
integer(C_INT64_T), intent(in) :: n
type(SWIGTYPE_p_SUNMemoryType), intent(in) :: memtype
type(SWIGTYPE_p_SUNMemoryHelper), intent(in) :: memhelper
type(C_PTR) :: queue
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT64_T) :: farg1 
integer(C_INT64_T) :: farg2 
type(SwigClassWrapper) :: farg3 
type(SwigClassWrapper) :: farg4 
type(C_PTR) :: farg5 
type(C_PTR) :: farg6 

farg1 = m
farg2 = n
farg3 = memtype%swigdata
farg4 = memhelper%swigdata
farg5 = queue
farg6 = sunctx
fresult = swigc_FSUNMatrix_MagmaDense(farg1, farg2, farg3, farg4, farg5, farg6)
call c_f_pointer(fresult, swig_result)
end function

function FSUNMatrix_MagmaDenseBlock(nblocks, m, n, memtype, memhelper, queue, sunctx) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNMatrix), pointer :: swig_result
integer(C_INT64_T), intent(in) :: nblocks
integer(C_INT64_T), intent(in) :: m
integer(C_INT64_T), intent(in) :: n
type(SWIGTYPE_p_SUNMemoryType), intent(in) :: memtype
type(SWIGTYPE_p_SUNMemoryHelper), intent(in) :: memhelper
type(C_PTR) :: queue
type(C_PTR) :: sunctx
type(C_PTR) :: fresult 
integer(C_INT64_T) :: farg1 
integer(C_INT64_T) :: farg2 
integer(C_INT64_T) :: farg3 
type(SwigClassWrapper) :: farg4 
type(SwigClassWrapper) :: farg5 
type(C_PTR) :: farg6 
type(C_PTR) :: farg7 

farg1 = nblocks
farg2 = m
farg3 = n
farg4 = memtype%swigdata
farg5 = memhelper%swigdata
farg6 = queue
farg7 = sunctx
fresult = swigc_FSUNMatrix_MagmaDenseBlock(farg1, farg2, farg3, farg4, farg5, farg6, farg7)
call c_f_pointer(fresult, swig_result)
end function

subroutine FSUNMatrix_MagmaDense_Print(a)
use, intrinsic :: ISO_C_BINDING
type(SUNMatrix), target, intent(inout) :: a
type(C_PTR) :: farg1 

farg1 = c_loc(a)
call swigc_FSUNMatrix_MagmaDense_Print(farg1)
end subroutine

function FSUNMatrix_MagmaDense_LData(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatrix_MagmaDense_LData(farg1)
swig_result = fresult
end function

function FSUNMatrix_MagmaDense_Rows(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatrix_MagmaDense_Rows(farg1)
swig_result = fresult
end function

function FSUNMatrix_MagmaDense_Columns(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatrix_MagmaDense_Columns(farg1)
swig_result = fresult
end function

function FSUNMatrix_MagmaDense_BlockRows(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatrix_MagmaDense_BlockRows(farg1)
swig_result = fresult
end function

function FSUNMatrix_MagmaDense_BlockColumns(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatrix_MagmaDense_BlockColumns(farg1)
swig_result = fresult
end function

function FSUNMatrix_MagmaDense_BlockLData(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatrix_MagmaDense_BlockLData(farg1)
swig_result = fresult
end function

function FSUNMatrix_MagmaDense_NumBlocks(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT64_T) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatrix_MagmaDense_NumBlocks(farg1)
swig_result = fresult
end function

function FSUNMatrix_MagmaDense_CopyToDevice(a, h_data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
real(C_DOUBLE), dimension(*), target, intent(inout) :: h_data
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(a)
farg2 = c_loc(h_data(1))
fresult = swigc_FSUNMatrix_MagmaDense_CopyToDevice(farg1, farg2)
swig_result = fresult
end function

function FSUNMatrix_MagmaDense_CopyFromDevice(a, h_data) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
real(C_DOUBLE), dimension(*), target, intent(inout) :: h_data
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(a)
farg2 = c_loc(h_data(1))
fresult = swigc_FSUNMatrix_MagmaDense_CopyFromDevice(farg1, farg2)
swig_result = fresult
end function

function FSUNMatGetID_MagmaDense(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(SUNMatrix_ID) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatGetID_MagmaDense(farg1)
swig_result = fresult
end function

function FSUNMatClone_MagmaDense(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
type(SUNMatrix), pointer :: swig_result
type(SUNMatrix), target, intent(inout) :: a
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatClone_MagmaDense(farg1)
call c_f_pointer(fresult, swig_result)
end function

subroutine FSUNMatDestroy_MagmaDense(a)
use, intrinsic :: ISO_C_BINDING
type(SUNMatrix), target, intent(inout) :: a
type(C_PTR) :: farg1 

farg1 = c_loc(a)
call swigc_FSUNMatDestroy_MagmaDense(farg1)
end subroutine

function FSUNMatZero_MagmaDense(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatZero_MagmaDense(farg1)
swig_result = fresult
end function

function FSUNMatCopy_MagmaDense(a, b) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
type(SUNMatrix), target, intent(inout) :: b
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 

farg1 = c_loc(a)
farg2 = c_loc(b)
fresult = swigc_FSUNMatCopy_MagmaDense(farg1, farg2)
swig_result = fresult
end function

function FSUNMatScaleAdd_MagmaDense(c, a, b) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
real(C_DOUBLE), intent(in) :: c
type(SUNMatrix), target, intent(inout) :: a
type(SUNMatrix), target, intent(inout) :: b
integer(C_INT) :: fresult 
real(C_DOUBLE) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c
farg2 = c_loc(a)
farg3 = c_loc(b)
fresult = swigc_FSUNMatScaleAdd_MagmaDense(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNMatScaleAddI_MagmaDense(c, a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
real(C_DOUBLE), intent(in) :: c
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT) :: fresult 
real(C_DOUBLE) :: farg1 
type(C_PTR) :: farg2 

farg1 = c
farg2 = c_loc(a)
fresult = swigc_FSUNMatScaleAddI_MagmaDense(farg1, farg2)
swig_result = fresult
end function

function FSUNMatMatvecSetup_MagmaDense(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatMatvecSetup_MagmaDense(farg1)
swig_result = fresult
end function

function FSUNMatMatvec_MagmaDense(a, x, y) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
type(N_Vector), target, intent(inout) :: x
type(N_Vector), target, intent(inout) :: y
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(a)
farg2 = c_loc(x)
farg3 = c_loc(y)
fresult = swigc_FSUNMatMatvec_MagmaDense(farg1, farg2, farg3)
swig_result = fresult
end function

function FSUNMatSpace_MagmaDense(a, lenrw, leniw) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
integer(C_INT) :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_LONG), dimension(*), target, intent(inout) :: lenrw
integer(C_LONG), dimension(*), target, intent(inout) :: leniw
integer(C_INT) :: fresult 
type(C_PTR) :: farg1 
type(C_PTR) :: farg2 
type(C_PTR) :: farg3 

farg1 = c_loc(a)
farg2 = c_loc(lenrw(1))
farg3 = c_loc(leniw(1))
fresult = swigc_FSUNMatSpace_MagmaDense(farg1, farg2, farg3)
swig_result = fresult
end function


function FSUNMatrix_MagmaDense_Data(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
type(SUNMatrix), target, intent(inout) :: a
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 

farg1 = c_loc(a)
fresult = swigc_FSUNMatrix_MagmaDense_Data(farg1)
call c_f_pointer(fresult, swig_result, [FSUNMatrix_MagmaDense_LData(a)])
end function

function FSUNMatrix_MagmaDense_BlockData(a) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
type(SUNMatrix), target, intent(inout) :: a
type(C_PTR) :: fresult 
type(C_PTR) :: farg1

farg1 = c_loc(a)
fresult = swigc_FSUNMatrix_MagmaDense_BlockData(farg1)
call c_f_pointer(fresult, swig_result, [FSUNMatrix_MagmaDense_NumBlocks(a)])
end function

function FSUNMatrix_MagmaDense_Block(a, k) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T), intent(in) :: k
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT64_T) :: farg2 

farg1 = c_loc(a)
farg2 = k
fresult = swigc_FSUNMatrix_MagmaDense_Block(farg1, farg2)
call c_f_pointer(fresult, swig_result,[FSUNMatrix_MagmaDense_LData(a)/FSUNMatrix_MagmaDense_NumBlocks(a)])
end function

function FSUNMatrix_MagmaDense_Column(a, j) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T), intent(in) :: j
type(C_PTR) :: fresult 
type(C_PTR) :: farg1 
integer(C_INT64_T) :: farg2 

farg1 = c_loc(a)
farg2 = j
fresult = swigc_FSUNMatrix_MagmaDense_Column(farg1, farg2)
call c_f_pointer(fresult, swig_result, [FSUNMatrix_MagmaDense_Rows(a)])
end function

function FSUNMatrix_MagmaDense_BlockColumn(a, k, j) &
result(swig_result)
use, intrinsic :: ISO_C_BINDING
real(C_DOUBLE), dimension(:), pointer :: swig_result
type(SUNMatrix), target, intent(inout) :: a
integer(C_INT64_T), intent(in) :: k
integer(C_INT64_T), intent(in) :: j
type(C_PTR) :: fresult
type(C_PTR) :: farg1
integer(C_INT64_T) :: farg2
integer(C_INT64_T) :: farg3

farg1 = c_loc(a)
farg2 = k
farg3 = j
fresult = swigc_FSUNMatrix_MagmaDense_BlockColumn(farg1, farg2, farg3)
call c_f_pointer(fresult, swig_result, [FSUNMatrix_MagmaDense_BlockRows(a)])
end function


end module
